# Generated by Django 2.0 on 2019-04-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_name', models.CharField(max_length=50)),
                ('novel_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NovelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('last_update_time', models.CharField(max_length=255)),
                ('read_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NovelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='novelinfo',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='novels.NovelType'),
        ),
        migrations.AddField(
            model_name='novel',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='novels.NovelType'),
        ),
    ]
