# Generated by Django 2.0 on 2019-04-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20190409_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='type_name',
            new_name='novel_type',
        ),
    ]
